-- lua/who5673_nasm/instructions.lua

return {
	-- Float commands (arithmetic):
	fadd = "Like `add` but used for float numbers, especially 80-bit float.\nExample: fadd st0, st1",
	fsub = "Like `sub` but used for floating point numbers.\nExample: fsub st0, st1    ; st0 = st0 - st1",
	fsubr = "The reverse of fsub.\nfsubr st0, st1    ; st0 = st1 - st0",
	fmul = "Like `mul` but used for floating point numbers.\nExample: fmul st0, st1",
	fdiv = "Like `div` but used for floating point numbers.\nExample: fdiv st0, st1    ; st0 = st0 / st1",
	fdivr = "The reverse of fdiv.\nfdivr st0, st1.   ; st0 = st1 / st0",
	-- Float commands (load ans store):
	fld = "Load something into Floating Point Unit stack (**default pushed target: st(0)** (unsigned).\nExample: fld dword 1.5)",
	fild = "Load integer as float onto Floating Point Unit stack",
	fst = "Stire float value from Floating Point Unit stack (without pop)",
	fstp = "Store float value from Floating Point Unit stack (and pop",
	fist = "Store Floating Point Unit float as integer (without pop)",
	fistp = "Store Floating Point Unit float as integer (and pop)",
	frndint = "Round st0 to an integer based on current Floating Point Unit rounding mode",
	fldcw = "Push a value into Floating Point Unit control word for dealing with exceptions, accuracy, rounding numbers,...\nSyntax: `fldcw [mem16]`. (**Hint: [variable] rounds toward zero with variable = 0x0F7F**).\n00 -> Round to nearest; 01 -> round down; 10 -> Round up; 11 -> Truncate\n. **Default: 0x037F(hex) = 895(dec)**.",
	-- Normal commands:
	mov = "Move data from source to destination",
	inc = "Increment operand by 1",
	dec = "Decrement operand by 1",
	add = "Add source to destination",
	sub = "Subtract source from destination",
	xor = "Bitwise XOR",
	and_ = "Bitwise AND",
	or_ = "Bitwise OR",
	cmp = "Compare operands",
	default = "This code must be at the first line of a NASM script if you combine with rel in order to combine and extern with C/C++ via gcc/g++.",
	to = "Specify the target st(i) to be added in Floating Point Unit stack, default thing used to add is st0.\n Example: fadd to st2",
	rel = "rel command: Use a relative address for something",
	neg = "Compute the **absolute value** (abs) of a register",
	lea = "lea command to work with memory",
	rep = "Repeat string operation",
	mul = "Multiply",
	div = "Divide (**unsigned**) 2 numbers",
	idiv = "Divide (**signed**) 2 numbers",
	int = "Interrupt",
	ret = "Return from procedure, **rax** is the most important return value if you create a label that returns an integer",
	push = "push to stack",
	pop = "pop from stack",
	shl = "Shift bits left (<<). Ex: 1 SHL 2",
	shr = "Shift bits right (>>). Ex: 8 SHR 1",
	syscall = "Call the system kernel",
	extern = "Declare external function (usually from libraries)",
	align = "Align N to optimize memory (common values: 16, 64)",
	movsb = "Copy bytes from src to dest (often with REP)",
	stosb = "Store bytes to dest (often with REP)",
	cmpsb = "Compare byte strings (often with REPNE)",
	repne = "Repeat while not equal (for CMPSB)",
	MOD = "Modulus operator (remainder). Example: 8 MOD 3 = 2",
	sete = "Set if equal (==). ZF = 1",
	setne = "Set if not equal (!=). ZF = 0",
	setg = "Set if greater (>). ZF = 0 and SF = OF",
	setge = "Set if greater or equal (>=). SF = OF",
	setl = "Set if less (<). SF ≠ OF",
	setle = "Set if less or equal (<=). ZF = 1 or SF ≠ OF",
	seta = "Set if above (unsigned >). CF = 0, ZF = 0",
	setb = "Set if below (unsigned <). CF = 1",
	setae = "Set if above or equal (unsigned ≥). CF = 0",
	setbe = "Set if below or equal (unsigned ≤). CF = 1 or ZF = 1",
	sets = "Set if negative. SF = 1",
	setns = "Set if non-negative. SF = 0",
	seto = "Set if overflow. OF = 1",
	setno = "Set if no overflow. OF = 0",
	setc = "Set if carry. CF = 1",
	setnc = "Set if no carry. CF = 0",
	setz = "Set if zero. ZF = 1 (same as SETE)",
	setnz = "Set if not zero. ZF = 0 (same as SETNE)",
	setp = "Set if parity even. PF = 1",
	setnp = "Set if parity odd. PF = 0",
	byte = "Used to compare the bytes of 2 things",
	-- Jump commands
	jmp = "Unconditional jump",
	je = "Jump if 2 value is equal",
	jne = "Jump if 2 value is not equal",
	jg = "Jump if one value is greater than another (use cmp to knwo)",
	jge = "Jump if one value is greater than or equ to another",
	jl = "Jump if one value is lower than another",
	jle = "Jump if one value is lower than or equal to another",
	loop = "loop = dec and jnz",
	-- Segment registers:
	cs = "Register cs (Code Segment)",
	ds = "Register ds (Data Segment)",
	ss = "Register ss (Stack Segment)",
	es = "Register es (Extra Segment)",
	fs = "Register fs",
	gs = "Register gs",
	-- Other important words
	[".data"] = ".data section (initialized data)",
	[".bss"] = ".bss section (uninitialized data or buffers)",
	[".text"] = ".text section (code)",
	["_start"] = "Program entry point",
	global = "Declare a symbol globally visible",
	db = "Define byte (1 byte)",
	dw = "Define word (2 bytes, 16-bit)",
	dd = "Define double word (4 bytes, 32-bit)",
	dq = "Define quad word (8 bytes, 64-bit)",
	dt = "Define ten bytes (80-bit, x87 float)",
	resb = "Reserve n bytes (uninitialized)",
	resw = "Reserve n words (2n bytes)",
	resd = "Reserve n double words (4n bytes)",
	resq = "Reserve n quad words (8n bytes)",
	equ = "Define constant (equate)",
	msg = "Common label for messages",
	buffer = "Common label for buffer",
	len = "Common label for string length",
}
